In [9]:
import numpy as np
import pandas as pd
import math

# cargar el dataframe
df = pd.read_csv("../data/datacrab.txt", delimiter= " ", decimal=".", encoding="utf-8")
df.head(8)

   input  color  spine  width  satell  weight
0      1      3      3   28.3       8    3050
1      2      4      3   22.5       0    1550
2      3      2      1   26.0       9    2300
3      4      4      3   24.8       0    2100
4      5      4      3   26.0       4    2600
5      6      3      3   23.8       0    2100
6      7      2      1   26.5       0    2350
7      8      4      2   24.7       0    1900

In [17]:
# cálculo de grupos según técnica

cw = df.width
n = len(cw)

# 1. Decidir el número de intervalos que vamos a utilizar

# regla de la raíz cuadrada

k1 = math.ceil(math.sqrt(n)) #parte entera superior de la raíz cuadrada de n
k1 

# scott
#Primero cálculo de la amplitud teórica
As = 3.5*cw.std()*n**(-1/3)
As
k3 = math.ceil((max(cw)-min(cw))/As)
k3

# sturges
k2 = math.ceil(1+math.log(n,2))

# FD
#Primero cálculo de la amplitud teórica
Afd= 2*(np.percentile(cw, 75)-np.percentile(cw, 25))*n**(-1/3)
k4 = math.ceil((max(cw)-min(cw))/Afd)

# 2. Decidir la amplitud de estos intervalos
# Como nuestros datos están expresados en mm con una precisión de una cifra decimal, debemos redondear por exceso a un cifra decimal el resultado obtenido. Por lo tanto, nuestra amplitud será de

A = (max(cw)-min(cw))/k1
A
A = 0.9

# 3. Acumular los extremos de los intervalos
L1 = min(cw)-(1/2)*0.1 #Primer extremo
#Resto de extremos
L = []
for i in range(k1):  
    L.append((L1+A*i))
    
# 4. Calcular el valor representativo de cada intervalo, su marca de clase
X1 = (L[0]+L[1])/2 #Primera marca de clase
#Resto de marcas de clase
X= []
for i in range(k1):
    X.append((X1+A*i))